import type { Tour } from '../types.js';

/** Tour catalog in English — mirror of pt-BR.js (same ids and structure). */
export const TOURS_EN: Tour[] = [
  {
    id: 'team-leader',
    icon: 'Users',
    title: 'Team with a leader (zero-config)',
    tagline: 'A leader that assembles and commands the team for you.',
    steps: [
      {
        id: 'leader',
        title: 'Create the team leader',
        body: 'Everything starts with a leader agent (Maestro Mode). It proposes the team, recruits, connects and distributes work on its own. I\'ll create it for you with one click.',
        action: { kind: 'createAgent', title: 'Líder', provider: 'claude', leader: true },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Líder' },
      },
      {
        id: 'brief',
        title: 'The briefing note',
        body: 'The project spec lives in a note connected to the team. I\'ll create a sample "Briefing" note — edit it with what you want to build.',
        action: { kind: 'createNote', title: 'Briefing', content: '# Briefing\n\nDescribe the project here: goal, scope and definition of done.\n' },
        check: { kind: 'nodeExists', nodeType: 'note', titleIncludes: 'Briefing' },
      },
      {
        id: 'brief-connect',
        title: 'Connect the note to the leader',
        body: 'Connecting the note gives the leader the project context. I\'ll make the connection for you.',
        action: { kind: 'connect', fromTitle: 'Briefing', toTitle: 'Líder' },
        check: { kind: 'edgeExists', fromTitle: 'Briefing', toTitle: 'Líder' },
      },
      {
        id: 'board',
        title: 'The task board',
        body: 'The team kanban: cards in To do/Doing/Done. I\'ll create the board and the first task assigned to the leader — it breaks down and distributes the rest.',
        action: { kind: 'createTasksBoard' },
      },
      {
        id: 'first-task',
        title: 'First task for the leader',
        body: 'I\'ll create the task "Assemble the team and start" assigned to the leader. It lands right in their terminal.',
        action: { kind: 'createTask', title: 'Assemble the team and start (read the Briefing note)', assigneeTitle: 'Líder' },
        check: { kind: 'taskExists', titleIncludes: 'Assemble the team' },
      },
      {
        id: 'talk',
        title: 'Give the order',
        body: 'In the leader\'s terminal, say: "read the Briefing note, propose the team and start". It recruits the agents, connects everything and works. The tour ends when the leader is on the canvas.',
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Líder' },
      },
    ],
  },
  {
    id: 'vigia-24-7',
    icon: 'Repeat',
    title: '24/7 worker (task watcher)',
    tagline: 'An agent that works nonstop, minute after minute.',
    steps: [
      {
        id: 'leader',
        title: 'The watcher',
        body: 'A leader agent stays on duty: every few minutes it checks the board, assigns whatever has no owner and recruits when people are missing.',
        action: { kind: 'createAgent', title: 'Vigia', provider: 'claude', leader: true },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Vigia' },
      },
      {
        id: 'board',
        title: 'The watched board',
        body: 'It needs a board to watch. I\'ll create the Tasks node for you.',
        action: { kind: 'createTasksBoard' },
      },
      {
        id: 'routine',
        title: 'The duty routine',
        body: 'I\'ll create the routine: every 5 minutes the watcher gets "check the board (orkestrai task list); assign what has no owner; recruit if someone is missing".',
        action: { kind: 'createRoutine', targetTitle: 'Vigia', prompt: 'Check the board with: orkestrai task list. Assign whatever has no owner. If an agent is missing, recruit (orkestrai recruit).', intervalMinutes: 5 },
        check: { kind: 'routineExists' },
      },
      {
        id: 'drop-task',
        title: 'Test with a task',
        body: 'Create any task on the board (or use "Do it for me") and watch: within 5 minutes the watcher picks it up and distributes it on its own.',
        action: { kind: 'createTask', title: 'Watcher test task' },
        check: { kind: 'taskExists', titleIncludes: 'Watcher' },
      },
    ],
  },
  {
    id: 'duas-features',
    icon: 'GitBranch',
    title: 'Two features in parallel, no conflicts',
    tagline: 'Two teams, two floors, zero stepping on toes.',
    steps: [
      {
        id: 'floor',
        title: 'Create a floor',
        body: 'A floor is an isolated copy of the project (git worktree) with its own branch. Team B works in it while team A stays on the main one. I\'ll create the "new-feature" floor for you.',
        action: { kind: 'createFloor', name: 'new-feature' },
        check: { kind: 'floorExists', nameIncludes: 'feature' },
      },
      {
        id: 'agents',
        title: 'One agent per front',
        body: 'I\'ll create two agents: one works on the main floor, the other on the new feature. Move the second to the floor layer (Floors panel in the bottom bar).',
        action: { kind: 'createAgent', title: 'Dev Principal', provider: 'claude' },
      },
      {
        id: 'agent-b',
        title: 'The feature agent',
        body: 'I\'ll create the B-front agent. In the Floors panel, switch the visible layer and drag it there — it starts working in the floor checkout.',
        action: { kind: 'createAgent', title: 'Dev Feature', provider: 'codex' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Dev Feature' },
      },
      {
        id: 'land',
        title: 'Merging back',
        body: 'When the feature is done: Floors panel → preview shows conflicts BEFORE the merge; land merges everything. Conflicts become a task for an agent to solve. Finish when the floor exists.',
        check: { kind: 'floorExists', nameIncludes: 'feature' },
      },
    ],
  },
  {
    id: 'qa-visual',
    icon: 'Workflow',
    title: 'Visual QA of your app',
    tagline: 'An agent that opens your app and tests it for real.',
    steps: [
      {
        id: 'portal',
        title: 'The portal (the agents\' browser)',
        body: 'The portal is an embedded browser the agents control. I\'ll create one pointing at your dev server — adjust the URL later if it isn\'t localhost:5173.',
        action: { kind: 'createPortal', url: 'http://localhost:5173', title: 'Portal App' },
        check: { kind: 'nodeExists', nodeType: 'portal' },
      },
      {
        id: 'qa',
        title: 'The QA agent',
        body: 'I\'ll create the agent that will test. Connect it to the portal so it can see the page.',
        action: { kind: 'createAgent', title: 'QA', provider: 'claude' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'QA' },
      },
      {
        id: 'connect',
        title: 'Connect QA to the portal',
        body: 'Connected, QA navigates, reads the DOM, runs JS and takes screenshots. I\'ll make the connection.',
        action: { kind: 'connect', fromTitle: 'QA', toTitle: 'Portal App' },
        check: { kind: 'edgeExists', fromTitle: 'QA', toTitle: 'Portal App' },
      },
      {
        id: 'test',
        title: 'Ask for the test',
        body: 'In QA\'s terminal: "open the portal, run the app\'s main flow, take a screenshot and tell me what broke". It executes and reports.',
      },
    ],
  },
  {
    id: 'pesquisa-resumo',
    icon: 'Search',
    title: 'Automated research with summary',
    tagline: 'The agent researches the web and writes the summary in a note.',
    steps: [
      {
        id: 'note',
        title: 'The summary note',
        body: 'I\'ll create the "Summary" note — where the agent writes the findings in bullet points.',
        action: { kind: 'createNote', title: 'Summary', content: '# Summary\n\n(research findings appear here in bullet points)\n' },
        check: { kind: 'nodeExists', nodeType: 'note', titleIncludes: 'Summary' },
      },
      {
        id: 'portal',
        title: 'The research portal',
        body: 'I\'ll create a portal open on Google — the agent uses it to read sources.',
        action: { kind: 'createPortal', url: 'https://www.google.com', title: 'Research Portal' },
        check: { kind: 'nodeExists', nodeType: 'portal' },
      },
      {
        id: 'agent',
        title: 'The researcher',
        body: 'I\'ll create the researcher agent and connect it to the portal and the note — portal to read, note to write.',
        action: { kind: 'createAgent', title: 'Researcher', provider: 'kimi' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Researcher' },
      },
      {
        id: 'connect',
        title: 'Working connections',
        body: 'I\'ll make both connections: Researcher ↔ Research Portal and Researcher ↔ Summary. Then say: "use the portal to read about X and write the summary in the note".',
        action: [
          { kind: 'connect', fromTitle: 'Researcher', toTitle: 'Research Portal' },
          { kind: 'connect', fromTitle: 'Researcher', toTitle: 'Summary' },
        ],
        check: { kind: 'edgeExists', fromTitle: 'Researcher', toTitle: 'Research Portal' },
      },
    ],
  },
  {
    id: 'inbox-arquivos',
    icon: 'FolderPlus',
    title: 'Self-processing file inbox',
    tagline: 'Drop files in the folder; the team processes them in batch.',
    steps: [
      {
        id: 'agent',
        title: 'The processor',
        body: 'I\'ll create the agent that will watch the ./inbox folder in your project (create the folder later if it doesn\'t exist).',
        action: { kind: 'createAgent', title: 'Processor', provider: 'claude' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Processor' },
      },
      {
        id: 'routine',
        title: 'The sweep routine',
        body: 'I\'ll create the routine: every 2 minutes it lists ./inbox, describes/classifies what\'s new, moves it to ./inbox/done and logs it on the board.',
        action: { kind: 'createRoutine', targetTitle: 'Processor', prompt: 'List ./inbox; for each new file, describe and classify it; move it to ./inbox/done and log it on the board with orkestrai task add.', intervalMinutes: 2 },
        check: { kind: 'routineExists' },
      },
      {
        id: 'test',
        title: 'Drop a file',
        body: 'Create the ./inbox folder in the project and drop any file. Within 2 minutes the processor describes, classifies and archives it.',
      },
    ],
  },
  {
    id: 'revisao-cruzada',
    icon: 'Cable',
    title: 'Cross-review between providers',
    tagline: 'Claude implements, Codex reviews. Two looks per change.',
    steps: [
      {
        id: 'dev',
        title: 'The implementer',
        body: 'I\'ll create the Claude that implements the changes.',
        action: { kind: 'createAgent', title: 'Claude Dev', provider: 'claude' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Claude Dev' },
      },
      {
        id: 'reviewer',
        title: 'The reviewer',
        body: 'I\'ll create the Codex reviewer — a different model reviewing with another perspective.',
        action: { kind: 'createAgent', title: 'Codex Reviewer', provider: 'codex' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Codex Reviewer' },
      },
      {
        id: 'connect',
        title: 'Connect the two',
        body: 'I\'ll make the connection: anything one asks the other travels through it (and it glows green while they talk).',
        action: { kind: 'connect', fromTitle: 'Claude Dev', toTitle: 'Codex Reviewer' },
        check: { kind: 'edgeExists', fromTitle: 'Claude Dev', toTitle: 'Codex Reviewer' },
      },
      {
        id: 'flow',
        title: 'The review flow',
        body: 'Tell Claude Dev: "implement X and ask Codex Reviewer for a review (orkestrai ask)". It implements, Codex critiques, the verdict comes back on the same rope.',
      },
    ],
  },
  {
    id: 'sentinela-deploy',
    icon: 'Rocket',
    title: 'Deploy & tests sentinel',
    tagline: 'Every hour: tests run, failures become a task + notification.',
    steps: [
      {
        id: 'agent',
        title: 'The sentinel',
        body: 'I\'ll create the agent that watches the project\'s health.',
        action: { kind: 'createAgent', title: 'Sentinel', provider: 'codex' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Sentinel' },
      },
      {
        id: 'board',
        title: 'The incident board',
        body: 'Failures become cards on the board. I\'ll create the Tasks node.',
        action: { kind: 'createTasksBoard' },
      },
      {
        id: 'routine',
        title: 'The hourly patrol',
        body: 'I\'ll create the routine: every 60 minutes it runs the tests; on failure, it opens a task for the team and notifies you on the desktop.',
        action: { kind: 'createRoutine', targetTitle: 'Sentinel', prompt: 'Run the project tests. On failure, open a task for the team (orkestrai task add) and notify the user (orkestrai notify).', intervalMinutes: 60 },
        check: { kind: 'routineExists' },
      },
      {
        id: 'test',
        title: 'Break it on purpose (optional)',
        body: 'Introduce an error in the code and watch the next patrol open the task and fire the native notification.',
      },
    ],
  },
  {
    id: 'preset-bootstrap',
    icon: 'Layers',
    title: 'Your framework preset',
    tagline: 'Build the team once; every new project starts ready.',
    steps: [
      {
        id: 'team',
        title: 'Build the default team',
        body: 'Create the team you use in every project (leader, devs, roles, bootstrap note with your framework conventions). I\'ll create the leader to start.',
        action: { kind: 'createAgent', title: 'Líder', provider: 'claude', leader: true },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Líder' },
      },
      {
        id: 'save',
        title: 'Save as preset',
        body: 'With the team assembled: pencil next to the workspace name in the sidebar → "Save as preset". The snapshot stores agents, layout, notes, roles and routines (no sessions).',
      },
      {
        id: 'use',
        title: 'Use it in the next project',
        body: 'When creating a new workspace (+ in the sidebar), pick the preset under "Start from a preset" — the whole team is instantiated in the project. Manage presets in Settings.',
      },
    ],
  },
  {
    id: 'pipeline-aprovacao',
    icon: 'Workflow',
    title: 'Write → review → approve pipeline',
    tagline: 'A 3-step flow with a pause for your OK.',
    steps: [
      {
        id: 'agents',
        title: 'Dev and reviewer',
        body: 'I\'ll create the two pipeline agents: the Dev (writes) and the Reviewer (critiques).',
        action: { kind: 'createAgent', title: 'Dev', provider: 'claude' },
      },
      {
        id: 'reviewer',
        title: 'The reviewer',
        body: 'I\'ll create the pipeline reviewer.',
        action: { kind: 'createAgent', title: 'Reviewer', provider: 'codex' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Reviewer' },
      },
      {
        id: 'flow',
        title: 'The 3-step flow',
        body: 'I\'ll create the Flow node: step 1 the Dev writes ({{input}} = your entry), step 2 the Reviewer critiques the Dev\'s output, step 3 pauses for YOUR approval.',
        action: {
          kind: 'createFlow',
          title: 'Review pipeline',
          steps: [
            { kind: 'agent', target: 'Dev', prompt: 'Write the solution for: {{input}}' },
            { kind: 'agent', target: 'Reviewer', prompt: 'Review critically, point out problems and improvements: {{input}}' },
            { kind: 'approval' },
          ],
        },
        check: { kind: 'nodeExists', nodeType: 'flow' },
      },
      {
        id: 'run',
        title: 'Run the flow',
        body: 'In the Flow node: write the input (e.g., "form validation with zod") and click Run. Watch the steps light up and approve at the final step.',
      },
    ],
  },
  {
    id: 'mcp-tools',
    icon: 'Cable',
    title: 'External tools via MCP',
    tagline: 'GitHub, docs and web in the agents\' hands — with one click.',
    steps: [
      {
        id: 'install',
        title: 'Install an MCP with 1 click',
        body: 'I\'ll install DeepWiki (documentation for any repository, zero configuration) in this workspace — no command, no token.',
        action: { kind: 'installMcp', key: 'deepwiki' },
        check: { kind: 'mcpInstalled', name: 'deepwiki' },
      },
      {
        id: 'market',
        title: 'The MCP marketplace',
        body: 'Skills page → MCPs tab: official curation (GitHub, Gmail, Figma, Drive, Vercel...) + the full registry. Ones that need a token open a guided dialog.',
      },
      {
        id: 'use',
        title: 'Use it in an agent',
        body: 'In an agent terminal (Claude/Kimi), ask something the MCP does — e.g., "ask DeepWiki how auth works in repository X". The tool appears natively in the agent.',
      },
    ],
  },
  {
    id: 'chained-flows',
    icon: 'Workflow',
    title: 'Chained flows',
    tagline: 'One flow triggers the next — compound pipelines and fan-out.',
    steps: [
      {
        id: 'first-flow',
        title: 'The first link',
        body: 'I create the "Research" Flow with an approval step — so you can simulate the stage without needing a real agent.',
        action: { kind: 'createFlow', title: 'Research', steps: [{ kind: 'approval' }] },
        check: { kind: 'nodeExists', nodeType: 'flow', titleIncludes: 'Research' },
      },
      {
        id: 'second-flow',
        title: 'The second link',
        body: 'I create the "Writing" Flow — when Research finishes successfully, its output becomes the Writing input by itself.',
        action: { kind: 'createFlow', title: 'Writing', steps: [{ kind: 'approval' }] },
        check: { kind: 'nodeExists', nodeType: 'flow', titleIncludes: 'Writing' },
      },
      {
        id: 'chain',
        title: 'Connect the two flows',
        body: 'I wire Research → Writing with an edge: the edge is what tells where the output goes when the flow finishes.',
        action: { kind: 'connect', fromTitle: 'Research', toTitle: 'Writing' },
        check: { kind: 'edgeExists', fromTitle: 'Research', toTitle: 'Writing' },
      },
      {
        id: 'run-chain',
        title: 'Run it and watch the chaining',
        body: 'On the Research Flow: click Run and then Approve. When it finishes, Writing fires by itself with the output — failure does not chain and cycles are blocked. Fan-out: connect a third flow to Research and both fire together. And the Sync button turns every agent connected to a flow into a step, in edge order.',
      },
    ],
  },

  {
    id: 'design-figma',
    icon: 'Palette',
    title: 'From Figma to code',
    tagline: 'Figma mockup becomes faithful UI with the designer agent.',
    steps: [
      {
        id: 'designer',
        title: 'The designer agent',
        body: 'I create the Designer (Claude) — it will read your visual references and generate the UI.',
        action: { kind: 'createAgent', title: 'Designer', provider: 'claude' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Designer' },
      },
      {
        id: 'image',
        title: 'The visual reference',
        body: 'Add an Image node (bottom bar), paste the Figma screenshot with Ctrl+V and connect it to the Designer — that is how it sees the mockup.',
      },
      {
        id: 'mcp',
        title: 'Figma MCP (optional and powerful)',
        body: 'Skills page → MCPs tab → search "Figma" and install with your token (Figma profile → Settings → Personal access tokens). With it the Designer reads frames, components and styles STRAIGHT from the file — no screenshots.',
      },
    ],
  },
  {
    id: 'managed-ports',
    icon: 'RadioTower',
    title: 'Release dev server ports',
    tagline: 'See and stop local listeners without leaving the canvas.',
    steps: [
      {
        id: 'portal',
        title: 'Register the app in a Portal',
        body: 'I create a local Portal on port 4173. This persisted link is what lets Orkestrai manage the port safely.',
        action: { kind: 'createPortal', url: 'http://localhost:4173', title: 'Dev Portal' },
        check: { kind: 'nodeExists', nodeType: 'portal', titleIncludes: 'Dev Portal' },
      },
      {
        id: 'server',
        title: 'Start your dev server',
        body: 'In the project terminal, start the app on the same port as the Portal. You can use `orkestrai port 4173` to pick a free port before starting the server.',
      },
      {
        id: 'panel',
        title: 'Open Ports and release the listener',
        body: 'In the bottom toolbar, immediately after Usage, open Ports. The process appears as in use; click the stop icon and confirm. The Portal stays saved for the next run.',
      },
    ],
  },
  {
    id: 'leader-dictation',
    icon: 'Mic',
    title: 'Dictate straight to the leader',
    tagline: 'Speak an instruction without finding the right canvas window.',
    steps: [
      {
        id: 'leader',
        title: 'Have a leader in the workspace',
        body: 'I create an agent in Maestro Mode. The voice orb always resolves that exact leader, even when it is on another floor.',
        action: { kind: 'createAgent', title: 'Voice Leader', provider: 'claude', leader: true },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Voice Leader' },
      },
      {
        id: 'record',
        title: 'Click the voice orb',
        body: 'Use the colored orb at the top right to start recording. It is the same microphone control inside the leader window, not a second dictation flow.',
      },
      {
        id: 'deliver',
        title: 'Stop and check the leader terminal',
        body: 'Click again to stop. After local transcription, the text goes directly into the selected leader terminal, ready for you to review or send.',
      },
    ],
  },
  {
    id: 'multilingual-spoken-replies',
    icon: 'Languages',
    title: 'Spoken replies in three languages',
    tagline: 'Choose, test and use a local voice suited to the language.',
    steps: [
      {
        id: 'choose',
        title: 'Choose the voice in Settings',
        body: 'Open Settings → Voice and select Portuguese (Brazil), English (United States) or Spanish (Latin America). Each option sets both the speaker and synthesis language.',
      },
      {
        id: 'preview',
        title: 'Listen before using it',
        body: 'Adjust speed from 0.75× to 1.50× and click Play preview. On first use, confirm the local download; after that all three voices work offline on macOS, Linux and Windows.',
      },
      {
        id: 'enable',
        title: 'Enable it on the agent',
        body: 'Return to the canvas and click the speaker in the terminal. The next reply is spoken with the selected voice, sentence by sentence, while dictation continues using the same Parakeet as before.',
      },
    ],
  },
  {
    id: 'team-template-library',
    icon: 'LayoutTemplate',
    title: 'Start with a ready-made team',
    tagline: 'Choose the stack and get agents, roles, skills, and a board already organized.',
    steps: [
      {
        id: 'preset-library',
        title: 'Open the preset library',
        body: 'Use the template icon in the sidebar or Presets in the bottom toolbar. Filter by Product, Development, Design and creative, Marketing and content, or Orkestrai.',
      },
      {
        id: 'create-or-merge',
        title: 'Create from scratch or add to the current team',
        body: 'New workspace prepares the selected project with layout, tasks, roles, and skills. The + button adds the same team to the current canvas without removing your nodes.',
      },
      {
        id: 'operate',
        title: 'Complete the team and track floors',
        body: 'In Roles → Catalog, install specialist functions. In Floors, track active agents, tasks, and Git state for each worktree before reviewing and landing.',
      },
    ],
  },
  {
    id: 'custom-board-stages',
    icon: 'Workflow',
    title: 'Adapt the board to your process',
    tagline: 'Replace a generic kanban with the stages your team actually uses.',
    steps: [
      {
        id: 'board',
        title: 'Create the work board',
        body: 'I create a Tasks node. It starts simple and can represent a campaign, content production, design project, or software delivery.',
        action: { kind: 'createTasksBoard' },
        check: { kind: 'nodeExists', nodeType: 'tasks', titleIncludes: 'Tasks' },
      },
      {
        id: 'stages',
        title: 'Define your stages',
        body: 'Click the columns icon in the board header. Rename, recolor, reorder, and add stages such as Ideas, Approval, and Published.',
      },
      {
        id: 'team-awareness',
        title: 'The team follows the same workflow',
        body: 'The lead and specialists receive the stages automatically. They create and move deliveries while you track everything visually.',
      },
    ],
  },
  {
    id: 'campaign-ready-team',
    icon: 'Palette',
    title: 'Launch a campaign with a ready team',
    tagline: 'Strategy, research, copy, and measurement arrive already organized.',
    steps: [
      {
        id: 'library',
        title: 'Open the Preset library',
        body: 'Choose Marketing and content → Campaign and launch. Brand and design and Content and SEO are ready for other kinds of work.',
      },
      {
        id: 'apply',
        title: 'Start new or add to this workspace',
        body: 'New workspace creates the team in another folder. The + button adds its lead and specialists to the current canvas without removing anything.',
      },
      {
        id: 'brief',
        title: 'Complete the brief and set the objective',
        body: 'Fill in objective, audience, offer, channels, deadline, and measurement in the created note. Then talk to the lead, which coordinates research, copy, distribution, and approval.',
      },
    ],
  },
  {
    id: 'orkestrai-consensus-team',
    icon: 'LayoutTemplate',
    title: 'Contribute to Orkestrai through consensus',
    tagline: 'Claude, Codex, and Kimi agree on the plan before execution.',
    steps: [
      {
        id: 'apply',
        title: 'Apply Orkestrai Contributing',
        body: 'In the Library’s Orkestrai category, create the complete team with a lead, two oracles, and Svelar, desktop, and QA/release specialists.',
      },
      {
        id: 'consensus',
        title: 'Run the consensus Flow',
        body: 'Codex proposes or audits architecture, Kimi reviews product, UX, and risks, and Claude synthesizes. Both oracles must answer APPROVED.',
      },
      {
        id: 'delivery',
        title: 'Only then distribute tasks',
        body: 'After approval, the lead records the decision, creates complete briefs, and tracks Review and Validation until tests, build, documentation, and changelog pass.',
      },
    ],
  },
];
