import type { Tour } from '../types.js';

/** Catalogo de tours en español — espejo de pt-BR.js (mismos ids y estructura). */
export const TOURS_ES: Tour[] = [
  {
    id: 'team-leader',
    icon: 'Users',
    title: 'Equipo con líder (zero-config)',
    tagline: 'Un líder que arma y comanda el equipo por ti.',
    steps: [
      {
        id: 'leader',
        title: 'Crea el líder del equipo',
        body: 'Todo empieza con un agente líder (Modo Maestro). Propone el equipo, recluta, conecta y distribuye el trabajo solo. Lo creo por ti con un clic.',
        action: { kind: 'createAgent', title: 'Líder', provider: 'claude', leader: true },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Líder' },
      },
      {
        id: 'brief',
        title: 'La nota de briefing',
        body: 'La spec del proyecto vive en una nota conectada al equipo. Creo una nota "Briefing" de ejemplo — edítala con lo que quieres construir.',
        action: { kind: 'createNote', title: 'Briefing', content: '# Briefing\n\nDescribe aquí el proyecto: objetivo, alcance y criterios de listo.\n' },
        check: { kind: 'nodeExists', nodeType: 'note', titleIncludes: 'Briefing' },
      },
      {
        id: 'brief-connect',
        title: 'Conecta la nota al líder',
        body: 'Conectar la nota le da al líder el contexto del proyecto. Hago la conexión por ti.',
        action: { kind: 'connect', fromTitle: 'Briefing', toTitle: 'Líder' },
        check: { kind: 'edgeExists', fromTitle: 'Briefing', toTitle: 'Líder' },
      },
      {
        id: 'board',
        title: 'El tablero de tareas',
        body: 'El kanban del equipo: tarjetas en Por hacer/Haciendo/Hecho. Creo el tablero y la primera tarea asignada al líder — él desglosa y distribuye el resto.',
        action: { kind: 'createTasksBoard' },
      },
      {
        id: 'first-task',
        title: 'Primera tarea para el líder',
        body: 'Creo la tarea "Armar el equipo y empezar" asignada al líder. Cae directo en su terminal.',
        action: { kind: 'createTask', title: 'Armar el equipo y empezar (lee la nota Briefing)', assigneeTitle: 'Líder' },
        check: { kind: 'taskExists', titleIncludes: 'Armar el equipo' },
      },
      {
        id: 'talk',
        title: 'Da la orden',
        body: 'En la terminal del líder, di: "lee la nota Briefing, propone el equipo y empieza". Recluta los agentes, conecta todo y trabaja. El tour termina cuando el líder esté en el canvas.',
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Líder' },
      },
    ],
  },
  {
    id: 'vigia-24-7',
    icon: 'Repeat',
    title: 'Empleado 24/7 (vigía de tareas)',
    tagline: 'Un agente que trabaja sin parar, minuto a minuto.',
    steps: [
      {
        id: 'leader',
        title: 'El vigía',
        body: 'Un agente líder queda de guardia: cada pocos minutos mira el tablero, asigna lo que no tiene dueño y recluta si falta gente.',
        action: { kind: 'createAgent', title: 'Vigia', provider: 'claude', leader: true },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Vigia' },
      },
      {
        id: 'board',
        title: 'El tablero vigilado',
        body: 'Necesita un tablero que vigilar. Creo el nodo Tareas por ti.',
        action: { kind: 'createTasksBoard' },
      },
      {
        id: 'routine',
        title: 'La rutina de guardia',
        body: 'Creo la rutina: cada 5 minutos el vigía recibe "revisa el tablero (orkestrai task list); asigna lo que no tenga dueño; si falta agente, recluta".',
        action: { kind: 'createRoutine', targetTitle: 'Vigia', prompt: 'Revisa el tablero con: orkestrai task list. Asigna lo que no tenga dueño. Si falta agente, recluta (orkestrai recruit).', intervalMinutes: 5 },
        check: { kind: 'routineExists' },
      },
      {
        id: 'drop-task',
        title: 'Prueba con una tarea',
        body: 'Crea cualquier tarea en el tablero (o usa "Hazlo por mí") y observa: en máximo 5 minutos el vigía la toma y la distribuye solo.',
        action: { kind: 'createTask', title: 'Tarea de prueba del vigía' },
        check: { kind: 'taskExists', titleIncludes: 'vigía' },
      },
    ],
  },
  {
    id: 'duas-features',
    icon: 'GitBranch',
    title: 'Dos features en paralelo sin conflicto',
    tagline: 'Dos equipos, dos pisos, cero pisotones.',
    steps: [
      {
        id: 'floor',
        title: 'Crea un piso',
        body: 'Un piso es una copia aislada del proyecto (worktree git) con rama propia. El equipo B trabaja en ella mientras el A sigue en la principal. Creo el piso "feature-nueva" por ti.',
        action: { kind: 'createFloor', name: 'feature-nueva' },
        check: { kind: 'floorExists', nameIncludes: 'feature' },
      },
      {
        id: 'agents',
        title: 'Un agente por frente',
        body: 'Creo dos agentes: uno trabaja en el piso principal, otro en la feature nueva. Mueve el segundo a la capa del piso (panel Pisos en la barra inferior).',
        action: { kind: 'createAgent', title: 'Dev Principal', provider: 'claude' },
      },
      {
        id: 'agent-b',
        title: 'El agente de la feature',
        body: 'Creo el agente del frente B. En el panel Pisos, cambia la capa visible y arrástralo ahí — empieza a trabajar en el checkout del piso.',
        action: { kind: 'createAgent', title: 'Dev Feature', provider: 'codex' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Dev Feature' },
      },
      {
        id: 'land',
        title: 'Uniendo de vuelta',
        body: 'Cuando la feature termine: panel Pisos → preview muestra conflictos ANTES del merge; el land une todo. Los conflictos se vuelven tarea para un agente. Concluye cuando el piso exista.',
        check: { kind: 'floorExists', nameIncludes: 'feature' },
      },
    ],
  },
  {
    id: 'qa-visual',
    icon: 'Workflow',
    title: 'QA visual de tu aplicación',
    tagline: 'Un agente que abre tu app y la prueba de verdad.',
    steps: [
      {
        id: 'portal',
        title: 'El portal (navegador de los agentes)',
        body: 'El portal es un navegador integrado que los agentes controlan. Creo uno apuntando a tu dev server — ajusta la URL después si no es localhost:5173.',
        action: { kind: 'createPortal', url: 'http://localhost:5173', title: 'Portal App' },
        check: { kind: 'nodeExists', nodeType: 'portal' },
      },
      {
        id: 'qa',
        title: 'El agente de QA',
        body: 'Creo el agente que va a probar. Conéctalo al portal para que vea la página.',
        action: { kind: 'createAgent', title: 'QA', provider: 'claude' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'QA' },
      },
      {
        id: 'connect',
        title: 'Conecta QA al portal',
        body: 'Conectado, QA navega, lee el DOM, ejecuta JS y toma capturas. Hago la conexión.',
        action: { kind: 'connect', fromTitle: 'QA', toTitle: 'Portal App' },
        check: { kind: 'edgeExists', fromTitle: 'QA', toTitle: 'Portal App' },
      },
      {
        id: 'test',
        title: 'Pide la prueba',
        body: 'En la terminal de QA: "abre el portal, haz el flujo principal de la app, toma captura y dime qué se rompió". Lo ejecuta y reporta.',
      },
    ],
  },
  {
    id: 'pesquisa-resumo',
    icon: 'Search',
    title: 'Investigación automatizada con resumen',
    tagline: 'El agente investiga en la web y escribe el resumen en una nota.',
    steps: [
      {
        id: 'note',
        title: 'La nota de resumen',
        body: 'Creo la nota "Resumen" — ahí el agente escribe los hallazgos en bullet points.',
        action: { kind: 'createNote', title: 'Resumen', content: '# Resumen\n\n(los hallazgos de la investigación aparecen aquí en bullet points)\n' },
        check: { kind: 'nodeExists', nodeType: 'note', titleIncludes: 'Resumen' },
      },
      {
        id: 'portal',
        title: 'El portal de investigación',
        body: 'Creo un portal abierto en Google — el agente lo usa para leer fuentes.',
        action: { kind: 'createPortal', url: 'https://www.google.com', title: 'Portal Investigación' },
        check: { kind: 'nodeExists', nodeType: 'portal' },
      },
      {
        id: 'agent',
        title: 'El investigador',
        body: 'Creo el agente investigador y lo conecto al portal y a la nota — portal para leer, nota para escribir.',
        action: { kind: 'createAgent', title: 'Investigador', provider: 'kimi' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Investigador' },
      },
      {
        id: 'connect',
        title: 'Conexiones de trabajo',
        body: 'Hago las dos conexiones: Investigador ↔ Portal Investigación e Investigador ↔ Resumen. Después di: "usa el portal para leer sobre X y escribe el resumen en la nota".',
        action: [
          { kind: 'connect', fromTitle: 'Investigador', toTitle: 'Portal Investigación' },
          { kind: 'connect', fromTitle: 'Investigador', toTitle: 'Resumen' },
        ],
        check: { kind: 'edgeExists', fromTitle: 'Investigador', toTitle: 'Portal Investigación' },
      },
    ],
  },
  {
    id: 'inbox-arquivos',
    icon: 'FolderPlus',
    title: 'Inbox de archivos procesada sola',
    tagline: 'Suelta archivos en la carpeta; el equipo los procesa en lote.',
    steps: [
      {
        id: 'agent',
        title: 'El procesador',
        body: 'Creo el agente que mirará la carpeta ./inbox de tu proyecto (crea la carpeta después si no existe).',
        action: { kind: 'createAgent', title: 'Procesador', provider: 'claude' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Procesador' },
      },
      {
        id: 'routine',
        title: 'La rutina de barrido',
        body: 'Creo la rutina: cada 2 minutos lista ./inbox, describe/clasifica lo nuevo, lo mueve a ./inbox/done y lo registra en el tablero.',
        action: { kind: 'createRoutine', targetTitle: 'Procesador', prompt: 'Lista ./inbox; para cada archivo nuevo, descríbelo y clasifícalo; muévelo a ./inbox/done y regístralo en el tablero con orkestrai task add.', intervalMinutes: 2 },
        check: { kind: 'routineExists' },
      },
      {
        id: 'test',
        title: 'Suelta un archivo',
        body: 'Crea la carpeta ./inbox en el proyecto y suelta cualquier archivo. En máximo 2 minutos el procesador lo describe, clasifica y archiva.',
      },
    ],
  },
  {
    id: 'revisao-cruzada',
    icon: 'Cable',
    title: 'Revisión cruzada entre providers',
    tagline: 'Claude implementa, Codex revisa. Dos miradas por cambio.',
    steps: [
      {
        id: 'dev',
        title: 'El implementador',
        body: 'Creo el Claude que implementa los cambios.',
        action: { kind: 'createAgent', title: 'Claude Dev', provider: 'claude' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Claude Dev' },
      },
      {
        id: 'reviewer',
        title: 'El revisor',
        body: 'Creo el Codex revisor — un modelo diferente revisando con otra mirada.',
        action: { kind: 'createAgent', title: 'Codex Reviewer', provider: 'codex' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Codex Reviewer' },
      },
      {
        id: 'connect',
        title: 'Conecta los dos',
        body: 'Hago la conexión: todo lo que uno pregunte al otro viaja por ella (y se enciende verde mientras conversan).',
        action: { kind: 'connect', fromTitle: 'Claude Dev', toTitle: 'Codex Reviewer' },
        check: { kind: 'edgeExists', fromTitle: 'Claude Dev', toTitle: 'Codex Reviewer' },
      },
      {
        id: 'flow',
        title: 'El flujo de revisión',
        body: 'Dile a Claude Dev: "implementa X y pide revisión a Codex Reviewer (orkestrai ask)". Implementa, Codex critica, el veredicto vuelve por la misma cuerda.',
      },
    ],
  },
  {
    id: 'sentinela-deploy',
    icon: 'Rocket',
    title: 'Centinela de deploy y pruebas',
    tagline: 'Cada hora: pruebas corriendo, fallos se vuelven tarea + notificación.',
    steps: [
      {
        id: 'agent',
        title: 'El centinela',
        body: 'Creo el agente que vigila la salud del proyecto.',
        action: { kind: 'createAgent', title: 'Centinela', provider: 'codex' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Centinela' },
      },
      {
        id: 'board',
        title: 'El tablero de incidentes',
        body: 'Los fallos se vuelven tarjetas en el tablero. Creo el nodo Tareas.',
        action: { kind: 'createTasksBoard' },
      },
      {
        id: 'routine',
        title: 'La ronda de cada hora',
        body: 'Creo la rutina: cada 60 minutos corre las pruebas; si fallan, abre tarea para el equipo y te notifica en el escritorio.',
        action: { kind: 'createRoutine', targetTitle: 'Centinela', prompt: 'Corre las pruebas del proyecto. Si fallan, abre una tarea para el equipo (orkestrai task add) y notifica al usuario (orkestrai notify).', intervalMinutes: 60 },
        check: { kind: 'routineExists' },
      },
      {
        id: 'test',
        title: 'Rómpelo a propósito (opcional)',
        body: 'Introduce un error en el código y mira la próxima ronda abrir la tarea y disparar la notificación nativa.',
      },
    ],
  },
  {
    id: 'preset-bootstrap',
    icon: 'Layers',
    title: 'Preset de tu framework',
    tagline: 'Arma el equipo una vez; todo proyecto nuevo nace listo.',
    steps: [
      {
        id: 'team',
        title: 'Arma el equipo estándar',
        body: 'Crea el equipo que usas en todo proyecto (líder, devs, roles, nota de bootstrap con las convenciones de tu framework). Creo el líder para empezar.',
        action: { kind: 'createAgent', title: 'Líder', provider: 'claude', leader: true },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Líder' },
      },
      {
        id: 'save',
        title: 'Guárdalo como preset',
        body: 'Con el equipo armado: lápiz junto al nombre del workspace en la barra lateral → "Guardar como preset". El snapshot guarda agentes, layout, notas, roles y rutinas (sin sesiones).',
      },
      {
        id: 'use',
        title: 'Úsalo en el próximo proyecto',
        body: 'Al crear un workspace nuevo (+ en la barra lateral), elige el preset en "Empezar de un preset" — el equipo entero nace instanciado en el proyecto. Gestiona presets en Configuración.',
      },
    ],
  },
  {
    id: 'pipeline-aprovacao',
    icon: 'Workflow',
    title: 'Pipeline escribe → revisa → aprueba',
    tagline: 'Flujo de 3 pasos con pausa para tu OK.',
    steps: [
      {
        id: 'agents',
        title: 'Dev y revisor',
        body: 'Creo los dos agentes del pipeline: el Dev (escribe) y el Revisor (critica).',
        action: { kind: 'createAgent', title: 'Dev', provider: 'claude' },
      },
      {
        id: 'reviewer',
        title: 'El revisor',
        body: 'Creo el revisor del pipeline.',
        action: { kind: 'createAgent', title: 'Revisor', provider: 'codex' },
        check: { kind: 'nodeExists', nodeType: 'terminal', titleIncludes: 'Revisor' },
      },
      {
        id: 'flow',
        title: 'El flujo de 3 pasos',
        body: 'Creo el nodo Flujo: paso 1 el Dev escribe ({{input}} = tu entrada), paso 2 el Revisor critica la salida del Dev, paso 3 pausa para TU aprobación.',
        action: {
          kind: 'createFlow',
          title: 'Pipeline revisión',
          steps: [
            { kind: 'agent', target: 'Dev', prompt: 'Escribe la solución para: {{input}}' },
            { kind: 'agent', target: 'Revisor', prompt: 'Revisa críticamente, señala problemas y mejoras: {{input}}' },
            { kind: 'approval' },
          ],
        },
        check: { kind: 'nodeExists', nodeType: 'flow' },
      },
      {
        id: 'run',
        title: 'Corre el flujo',
        body: 'En el nodo Flujo: escribe la entrada (ej.: "validación de formulario con zod") y haz clic en Correr. Mira los pasos encenderse y aprueba en el paso final.',
      },
    ],
  },
  {
    id: 'mcp-tools',
    icon: 'Cable',
    title: 'Tools externas vía MCP',
    tagline: 'GitHub, docs y web en manos de los agentes — con un clic.',
    steps: [
      {
        id: 'install',
        title: 'Instala un MCP con 1 clic',
        body: 'Instalo DeepWiki (documentación de cualquier repositorio, sin configurar nada) en este workspace — sin comando, sin token.',
        action: { kind: 'installMcp', key: 'deepwiki' },
        check: { kind: 'mcpInstalled', name: 'deepwiki' },
      },
      {
        id: 'market',
        title: 'El marketplace de MCPs',
        body: 'Página Skills → pestaña MCPs: curaduría oficial (GitHub, Gmail, Figma, Drive, Vercel...) + registry completo. Los que piden token abren un diálogo guiado.',
        action: { kind: 'openPage', path: '/skills?workspace={workspace}' },
      },
      {
        id: 'use',
        title: 'Úsalo en un agente',
        body: 'En una terminal de agente (Claude/Kimi), pide algo que el MCP haga — ej.: "pregúntale a DeepWiki cómo funciona el auth del repositorio X". La tool aparece nativa en el agente.',
      },
    ],
  },
  {
    id: 'chained-flows',
    icon: 'Workflow',
    title: 'Flujos encadenados',
    tagline: 'Un flujo dispara el siguiente — pipelines compuestos y fan-out.',
    steps: [
      {
        id: 'first-flow',
        title: 'El primer eslabón',
        body: 'Creo el Flujo "Investigación" con un paso de aprobación — así simulas la etapa sin necesitar un agente real.',
        action: { kind: 'createFlow', title: 'Investigación', steps: [{ kind: 'approval' }] },
        check: { kind: 'nodeExists', nodeType: 'flow', titleIncludes: 'Investigación' },
      },
      {
        id: 'second-flow',
        title: 'El segundo eslabón',
        body: 'Creo el Flujo "Redacción" — cuando Investigación termine con éxito, su salida se vuelve la entrada de Redacción sola.',
        action: { kind: 'createFlow', title: 'Redacción', steps: [{ kind: 'approval' }] },
        check: { kind: 'nodeExists', nodeType: 'flow', titleIncludes: 'Redacción' },
      },
      {
        id: 'chain',
        title: 'Conecta los dos flujos',
        body: 'Uno Investigación → Redacción con una arista: la arista es la que dice a dónde va la salida cuando el flujo termina.',
        action: { kind: 'connect', fromTitle: 'Investigación', toTitle: 'Redacción' },
        check: { kind: 'edgeExists', fromTitle: 'Investigación', toTitle: 'Redacción' },
      },
      {
        id: 'run-chain',
        title: 'Ejecuta y mira el encadenamiento',
        body: 'En el Flujo Investigación: haz clic en Ejecutar y luego Aprobar. Cuando termina, Redacción dispara sola con la salida — el fallo no encadena y los ciclos se bloquean. Fan-out: conecta un tercer flujo a Investigación y los dos disparan juntos. Y el botón Sincronizar convierte cada agente conectado a un flujo en paso, en el orden de las aristas.',
      },
    ],
  },
];
